### ISSUE TITLE
attempted download, received error: "VIRUS DETECTED"

### ISSUE THREAD

**Issue by thedavidyoungblood** [pavanjava/bootstrap-rag#71]
Via Chrome on Windows... Not going to `git-clone` this until that's resolved.

**Comment by pavanjava** [comment]
okay let me check it.

**Comment by pavanjava** [comment]
@thedavidyoungblood : can put your screenshot how you are cloning the repo. I tried from git cli and the chrome download source nowhere I found the issue. please show us the procedure so that it will be easy to troubleshoot.

![image](https://github.com/user-attachments/assets/dd73c478-7740-4522-9a3a-872827648a0d)
![image](https://github.com/user-attachments/assets/4ae7d9bd-3748-4269-9fd0-c02356d12463)

**Comment by pavanjava** [comment]
closing the issue as there is no response and as per the testing conducted the app is working normal. please report us in-case you still face issues.

**Comment by thedavidyoungblood** [comment]
resolved (for me)
